# Generated by Django 4.1.7 on 2023-02-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netijti_app", "0006_sector_namear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector", name="description", field=models.TextField(null=True),
        ),
    ]
